### PR TITLE
Replace deprecated HMSET with HSET in examples

### PR DESCRIPTION
**Pull request by randommm**
removing deprecated commands

### CODE REVIEW

**Comment by hwware** [comment]
I do not recommend removing any deprecated commands right now. Maybe in later version, we can consider this.

**Review by zuiderkwast — APPROVED** [review]
The change is updating an example to avoid use of the deprecated command in the example.

The change is good, but the description in the pull request is very bad IMO. Other reviewers have understood the description as if the documentation for the deprecated command is deleted.

Thanks for the PR and please use a better title and description next time.

**Comment by stockholmux** [comment]
I agree with @zuiderkwast. 
@randommm Would you be able to update the PR description and comment? 

Also, the DCO bot is not happy. Would you be able to sign off your commits?

**Comment by randommm** [comment]
@zuiderkwast should be okay now

**Review by zuiderkwast — APPROVED** [review]
OK, looks good.

From the title, it looks like we're removing the documentation of HMSET completely, but we just remove it from some examples. I'll edit the title again.

**Pull request merged**
